mkdir bin
mkdir bin/win64
mkdir bin/linux64
mkdir bin/osx
cd bin/win64
wget https://github.com/pbca26/komodod/releases/download/cd_release_4c1f3bb_tokens/komodo_4c1f3bb_tokens_win.zip
unzip komodo_4c1f3bb_tokens_win.zip
rm komodo_4c1f3bb_tokens_win.zip
cd ../linux64
wget https://github.com/pbca26/komodod/releases/download/cd_release_4c1f3bb_tokens/komodo_4c1f3bb_tokens_linux.zip
unzip komodo_4c1f3bb_tokens_linux.zip
rm komodo_4c1f3bb_tokens_linux.zip
cd ../osx
wget https://github.com/pbca26/komodod/releases/download/cd_release_4c1f3bb_tokens/komodo_4c1f3bb_tokens_osx.zip
unzip komodo_4c1f3bb_tokens_osx.zip
rm komodo_4c1f3bb_tokens_osx.zip